// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAcxess.ProjectContext
{
    public partial interface IProjectContextProcedures
    {
        Task<List<usp_GetSequenceResult>> usp_GetSequenceAsync(string SeqName, string Seq, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
